MOVEMENTS = [
    "Passive Hang",
    "Support Hold",
    "Hollow Body Hold",
    "Squats",
    "Push Ups",
    "Row",
    "Pull Ups",
    "Crow Pose",
    "Dips",
    "Pike Push Ups",
    "L-Sit",
    "RTO Ring Support Hold",
    "Pistol Squats",
    "Bulgarian Push Ups",
    "One-Arm Push Ups",
    "Archer Pull Ups",
    "Bulgarian Dips",
    "Dragon Squats",
    "Ring Muscle Ups",
    "Handstand",
    "Front Lever",
    "Handstand Push Ups",
    "One-Arm Chin Up",
    "Side Split",
    "V-Sit",
    "Press Handstand",
    "Back Lever Pulls",
    "Front Lever Pulls",
    "Planche"
]