"""add missing value columns to ascendant_stats

Revision ID: d7571156d2dc
Revises: fix_all_missing_cols
Create Date: 2025-07-28 22:42:40.561031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7571156d2dc'
down_revision: Union[str, Sequence[str], None] = 'fix_all_missing_cols'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.alter_column('ascendant_stats', 'ascendant_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'str_xp',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'end_xp',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'tech_xp',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'str_value',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'end_value',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'tech_value',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_ascendant_stats_ascendant_id', 'ascendant_stats', ['ascendant_id'], unique=False)
    op.create_unique_constraint(None, 'ascendant_stats', ['ascendant_id'])
    op.drop_constraint(op.f('ascendant_stats_ascendant_id_fkey'), 'ascendant_stats', type_='foreignkey')
    op.create_foreign_key(None, 'ascendant_stats', 'ascendants', ['ascendant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_ascendants_aura'), 'ascendants', ['aura'], unique=False)
    op.create_index(op.f('ix_ascendants_last_login'), 'ascendants', ['last_login'], unique=False)
    op.add_column('awakening_quests', sa.Column('target_movement_id', sa.Integer(), nullable=True))
    op.add_column('awakening_quests', sa.Column('target_movement', sa.String(length=100), nullable=True))
    op.add_column('awakening_quests', sa.Column('target_reps', sa.Integer(), nullable=True))
    op.add_column('awakening_quests', sa.Column('target_time', sa.Integer(), nullable=True))
    op.add_column('awakening_quests', sa.Column('target_distance', sa.Integer(), nullable=True))
    op.add_column('awakening_quests', sa.Column('difficulty_level', sa.String(length=20), nullable=False))
    op.add_column('awakening_quests', sa.Column('parameters', sa.JSON(), nullable=True))
    op.add_column('awakening_quests', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('awakening_quests', sa.Column('progress_reps', sa.Integer(), nullable=False))
    op.add_column('awakening_quests', sa.Column('progress_time', sa.Integer(), nullable=False))
    op.add_column('awakening_quests', sa.Column('progress_distance', sa.Integer(), nullable=False))
    op.alter_column('awakening_quests', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('awakening_quests', 'session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('awakening_quests', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('awakening_quests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index('idx_awakening_quests_movement', 'awakening_quests', ['target_movement_id'], unique=False)
    op.create_index('idx_awakening_quests_session', 'awakening_quests', ['session_id'], unique=False)
    op.create_index('idx_awakening_quests_type_status', 'awakening_quests', ['quest_type', 'status'], unique=False)
    op.create_index(op.f('ix_awakening_quests_quest_type'), 'awakening_quests', ['quest_type'], unique=False)
    op.create_index(op.f('ix_awakening_quests_session_id'), 'awakening_quests', ['session_id'], unique=False)
    op.create_index(op.f('ix_awakening_quests_status'), 'awakening_quests', ['status'], unique=False)
    op.drop_column('awakening_quests', 'is_completed')
    op.drop_column('awakening_quests', 'updated_at')
    op.drop_column('awakening_quests', 'current_progress')
    op.drop_column('awakening_quests', 'description')
    op.drop_column('awakening_quests', 'target_value')
    op.add_column('awakening_rewards', sa.Column('shadow_keys', sa.Integer(), nullable=False))
    op.add_column('awakening_rewards', sa.Column('xp_gained', sa.Integer(), nullable=False))
    op.add_column('awakening_rewards', sa.Column('stat_points', sa.Integer(), nullable=False))
    op.add_column('awakening_rewards', sa.Column('aura_change', sa.Integer(), nullable=False))
    op.add_column('awakening_rewards', sa.Column('streak_bonus', sa.Integer(), nullable=False))
    op.alter_column('awakening_rewards', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('awakening_rewards', 'session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('awakening_rewards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index('idx_awakening_rewards_session', 'awakening_rewards', ['session_id'], unique=False)
    op.create_index(op.f('ix_awakening_rewards_session_id'), 'awakening_rewards', ['session_id'], unique=False)
    op.drop_column('awakening_rewards', 'reward_type')
    op.drop_column('awakening_rewards', 'earned_at')
    op.drop_column('awakening_rewards', 'reward_value')
    op.drop_column('awakening_rewards', 'updated_at')
    op.add_column('awakening_sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('awakening_sessions', sa.Column('tier_level', sa.String(length=20), nullable=False))
    op.add_column('awakening_sessions', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('awakening_sessions', sa.Column('reset_used', sa.Boolean(), nullable=False))
    op.add_column('awakening_sessions', sa.Column('reset_at', sa.DateTime(), nullable=True))
    op.alter_column('awakening_sessions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('awakening_sessions_id_seq'::regclass)"))
    op.alter_column('awakening_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('awakening_sessions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index('idx_awakening_sessions_status', 'awakening_sessions', ['status'], unique=False)
    op.create_index('idx_awakening_sessions_user_date', 'awakening_sessions', ['user_id', 'session_date'], unique=False)
    op.create_index(op.f('ix_awakening_sessions_session_date'), 'awakening_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_awakening_sessions_status'), 'awakening_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_awakening_sessions_user_id'), 'awakening_sessions', ['user_id'], unique=False)
    op.drop_constraint(op.f('awakening_sessions_ascendant_id_fkey'), 'awakening_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'awakening_sessions', 'ascendants', ['user_id'], ['id'])
    op.drop_column('awakening_sessions', 'ascendant_id')
    op.drop_column('awakening_sessions', 'is_completed')
    op.drop_column('awakening_sessions', 'updated_at')
    op.add_column('daily_modifiers', sa.Column('modifier_date', sa.Date(), nullable=False))
    op.add_column('daily_modifiers', sa.Column('modifier_type', sa.String(length=30), nullable=False))
    op.add_column('daily_modifiers', sa.Column('xp_bonus', sa.Float(), nullable=False))
    op.add_column('daily_modifiers', sa.Column('skill_point_bonus', sa.Float(), nullable=False))
    op.add_column('daily_modifiers', sa.Column('modifier_data', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_daily_modifiers_date'), table_name='daily_modifiers')
    op.create_index('idx_daily_modifiers_date', 'daily_modifiers', ['modifier_date'], unique=False)
    op.create_index('idx_daily_modifiers_active', 'daily_modifiers', ['is_active'], unique=False)
    op.create_index('idx_daily_modifiers_type', 'daily_modifiers', ['modifier_type'], unique=False)
    op.create_index(op.f('ix_daily_modifiers_modifier_date'), 'daily_modifiers', ['modifier_date'], unique=True)
    op.drop_column('daily_modifiers', 'date')
    op.alter_column('dungeon_keys', 'ascendant_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_dungeon_keys_ascendant_id'), table_name='dungeon_keys')
    op.create_index('idx_dungeon_keys_ascendant_type', 'dungeon_keys', ['ascendant_id', 'key_type'], unique=False)
    op.drop_constraint(op.f('dungeon_keys_ascendant_id_fkey'), 'dungeon_keys', type_='foreignkey')
    op.create_foreign_key(None, 'dungeon_keys', 'ascendants', ['ascendant_id'], ['id'], ondelete='CASCADE')
    op.add_column('dungeon_level_unlocks', sa.Column('required_ascendant_level', sa.Integer(), nullable=False))
    op.add_column('dungeon_level_unlocks', sa.Column('required_aura', sa.Integer(), nullable=False))
    op.add_column('dungeon_level_unlocks', sa.Column('required_skill_tree_progress', sa.Integer(), nullable=False))
    op.add_column('dungeon_level_unlocks', sa.Column('required_previous_completion', sa.Boolean(), nullable=False))
    op.add_column('dungeon_level_unlocks', sa.Column('unlock_description', sa.Text(), nullable=False))
    op.add_column('dungeon_level_unlocks', sa.Column('is_enabled', sa.Boolean(), nullable=False))
    op.add_column('dungeon_level_unlocks', sa.Column('unlock_data', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_dungeon_level_unlocks_ascendant_id'), table_name='dungeon_level_unlocks')
    op.create_index('idx_dungeon_unlocks_ascendant_level', 'dungeon_level_unlocks', ['required_ascendant_level'], unique=False)
    op.create_index('idx_dungeon_unlocks_aura', 'dungeon_level_unlocks', ['required_aura'], unique=False)
    op.create_index('idx_dungeon_unlocks_enabled', 'dungeon_level_unlocks', ['is_enabled'], unique=False)
    op.create_index('idx_dungeon_unlocks_level', 'dungeon_level_unlocks', ['dungeon_level'], unique=False)
    op.create_index(op.f('ix_dungeon_level_unlocks_dungeon_level'), 'dungeon_level_unlocks', ['dungeon_level'], unique=True)
    op.drop_constraint(op.f('dungeon_level_unlocks_ascendant_id_fkey'), 'dungeon_level_unlocks', type_='foreignkey')
    op.drop_column('dungeon_level_unlocks', 'ascendant_id')
    op.drop_column('dungeon_level_unlocks', 'unlocked_at')
    op.alter_column('dungeon_progress', 'ascendant_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('dungeon_progress', 'total_completions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dungeon_progress', 'total_shadow_keys_spent',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dungeon_progress', 'total_shadow_essence_earned',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_dungeon_progress_ascendant_id'), table_name='dungeon_progress')
    op.create_index('idx_dungeon_progress_ascendant', 'dungeon_progress', ['ascendant_id'], unique=False)
    op.create_index('idx_dungeon_progress_completions', 'dungeon_progress', ['total_completions'], unique=False)
    op.create_index('idx_dungeon_progress_last_completion', 'dungeon_progress', ['last_completion_date'], unique=False)
    op.create_index('idx_dungeon_progress_level', 'dungeon_progress', ['highest_level_completed'], unique=False)
    op.create_unique_constraint(None, 'dungeon_progress', ['ascendant_id'])
    op.drop_constraint(op.f('dungeon_progress_ascendant_id_fkey'), 'dungeon_progress', type_='foreignkey')
    op.create_foreign_key(None, 'dungeon_progress', 'ascendants', ['ascendant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dungeon_progress', 'last_completed_at')
    op.add_column('dungeon_rewards', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('dungeon_rewards', sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('dungeon_rewards', 'reward_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('idx_dungeon_rewards_ascendant_id'), table_name='dungeon_rewards')
    op.create_index('idx_dungeon_rewards_applied', 'dungeon_rewards', ['applied_at'], unique=False)
    op.create_index('idx_dungeon_rewards_ascendant', 'dungeon_rewards', ['ascendant_id'], unique=False)
    op.create_index('idx_dungeon_rewards_session', 'dungeon_rewards', ['session_id'], unique=False)
    op.create_index('idx_dungeon_rewards_type', 'dungeon_rewards', ['reward_type'], unique=False)
    op.drop_constraint(op.f('dungeon_rewards_ascendant_id_fkey'), 'dungeon_rewards', type_='foreignkey')
    op.drop_constraint(op.f('dungeon_rewards_session_id_fkey'), 'dungeon_rewards', type_='foreignkey')
    op.create_foreign_key(None, 'dungeon_rewards', 'dungeon_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dungeon_rewards', 'ascendants', ['ascendant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dungeon_rewards', 'earned_at')
    op.drop_column('dungeon_rewards', 'reward_value')
    op.alter_column('dungeon_sessions', 'shadow_keys_spent',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dungeon_sessions', 'session_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_dungeon_sessions_ascendant_id'), table_name='dungeon_sessions')
    op.drop_index(op.f('ix_dungeon_sessions_session_id'), table_name='dungeon_sessions')
    op.drop_index(op.f('idx_dungeon_sessions_status'), table_name='dungeon_sessions')
    op.create_index('idx_dungeon_sessions_status', 'dungeon_sessions', ['session_status'], unique=False)
    op.create_index('idx_dungeon_sessions_ascendant', 'dungeon_sessions', ['ascendant_id'], unique=False)
    op.create_index('idx_dungeon_sessions_expires', 'dungeon_sessions', ['expires_at'], unique=False)
    op.create_index('idx_dungeon_sessions_keys_spent', 'dungeon_sessions', ['shadow_keys_spent'], unique=False)
    op.create_index('idx_dungeon_sessions_level', 'dungeon_sessions', ['dungeon_level'], unique=False)
    op.create_index(op.f('ix_dungeon_sessions_ascendant_id'), 'dungeon_sessions', ['ascendant_id'], unique=False)
    op.create_index(op.f('ix_dungeon_sessions_dungeon_level'), 'dungeon_sessions', ['dungeon_level'], unique=False)
    op.drop_column('dungeon_sessions', 'status')
    op.drop_column('dungeon_sessions', 'session_id')
    op.drop_column('dungeon_sessions', 'started_at')
    op.drop_column('dungeon_sessions', 'session_data')
    op.add_column('dungeon_trials', sa.Column('trial_type', sa.String(length=50), nullable=False))
    op.add_column('dungeon_trials', sa.Column('movement_id', sa.Integer(), nullable=True))
    op.add_column('dungeon_trials', sa.Column('required_reps', sa.Integer(), nullable=False))
    op.add_column('dungeon_trials', sa.Column('trial_status', sa.String(length=20), nullable=False))
    op.add_column('dungeon_trials', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dungeon_trials', sa.Column('trial_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_dungeon_trials_session_id'), table_name='dungeon_trials')
    op.create_index('idx_dungeon_trials_completed', 'dungeon_trials', ['is_completed'], unique=False)
    op.create_index('idx_dungeon_trials_number', 'dungeon_trials', ['trial_number'], unique=False)
    op.create_index('idx_dungeon_trials_session', 'dungeon_trials', ['session_id'], unique=False)
    op.create_index('idx_dungeon_trials_started', 'dungeon_trials', ['started_at'], unique=False)
    op.create_index('idx_dungeon_trials_status', 'dungeon_trials', ['trial_status'], unique=False)
    op.create_index('idx_dungeon_trials_type', 'dungeon_trials', ['trial_type'], unique=False)
    op.drop_constraint(op.f('dungeon_trials_session_id_fkey'), 'dungeon_trials', type_='foreignkey')
    op.create_foreign_key(None, 'dungeon_trials', 'dungeon_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dungeon_trials', 'target_reps')
    op.drop_column('dungeon_trials', 'exercise_name')
    op.alter_column('incursion_participants_v2', 'incursion_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('incursion_participants_v2', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('incursions_v2', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.add_column('movement_categories', sa.Column('primary_stat', sa.Enum('STR', 'END', 'TECH', name='stat_enum'), nullable=False))
    op.alter_column('movement_categories', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_movement_categories_category_id'), table_name='movement_categories')
    op.drop_index(op.f('ix_movement_categories_id'), table_name='movement_categories')
    op.create_unique_constraint(None, 'movement_categories', ['name'])
    op.create_unique_constraint(None, 'movement_categories', ['id'])
    op.drop_column('movement_categories', 'description')
    op.drop_column('movement_categories', 'category_id')
    op.add_column('movements', sa.Column('stat_reward_type', sa.Enum('STR', 'END', 'TECH', name='stat_enum'), nullable=False))
    op.alter_column('movements', 'node_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('movements', 'xp_per_rep',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index('idx_movements_name', 'movements', ['name'], unique=False)
    op.create_index('idx_movements_node_id', 'movements', ['node_id'], unique=False)
    op.create_index('idx_movements_node_name_unique', 'movements', ['node_id', 'name'], unique=True)
    op.drop_constraint(op.f('movements_node_id_fkey'), 'movements', type_='foreignkey')
    op.create_foreign_key(None, 'movements', 'skill_tree_nodes', ['node_id'], ['id'])
    op.alter_column('quest_completions', 'ascendant_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('quest_completions', 'quest_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_quest_completions_ascendant_id'), table_name='quest_completions')
    op.drop_index(op.f('idx_quest_completions_completed_at'), table_name='quest_completions')
    op.create_index('idx_quest_completions_ascendant_date', 'quest_completions', ['ascendant_id', 'created_at'], unique=False)
    op.create_unique_constraint(None, 'quest_completions', ['quest_id'])
    op.drop_constraint(op.f('quest_completions_ascendant_id_fkey'), 'quest_completions', type_='foreignkey')
    op.create_foreign_key(None, 'quest_completions', 'ascendants', ['ascendant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quest_completions', 'quests', ['quest_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quest_completions', 'xp_earned')
    op.drop_column('quest_completions', 'completed_at')
    op.add_column('quests', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('quests', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('quests', 'ascendant_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('quests', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('quests', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('idx_quests_ascendant_id'), table_name='quests')
    op.drop_index(op.f('idx_quests_expires_at'), table_name='quests')
    op.drop_index(op.f('ix_quests_quest_id'), table_name='quests')
    op.create_index('idx_quests_ascendant_status', 'quests', ['ascendant_id', 'status'], unique=False)
    op.create_index(op.f('ix_quests_source'), 'quests', ['source'], unique=False)
    op.create_index(op.f('ix_quests_status'), 'quests', ['status'], unique=False)
    op.drop_constraint(op.f('quests_ascendant_id_fkey'), 'quests', type_='foreignkey')
    op.create_foreign_key(None, 'quests', 'ascendants', ['ascendant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quests', 'xp_reward')
    op.drop_column('quests', 'quest_id')
    op.drop_column('quests', 'target_reps')
    op.drop_column('quests', 'target_exercise')
    op.drop_column('quests', 'expires_at')
    op.add_column('skill_tree_nodes', sa.Column('required_ascendant_level', sa.Integer(), nullable=False))
    op.add_column('skill_tree_nodes', sa.Column('required_str_points', sa.Integer(), nullable=False))
    op.add_column('skill_tree_nodes', sa.Column('required_end_points', sa.Integer(), nullable=False))
    op.add_column('skill_tree_nodes', sa.Column('required_tech_points', sa.Integer(), nullable=False))
    op.create_index('idx_skill_tree_nodes_category_level_unique', 'skill_tree_nodes', ['category_id', 'level'], unique=True)
    op.create_index('idx_skill_tree_nodes_level', 'skill_tree_nodes', ['level'], unique=False)
    op.drop_constraint(op.f('skill_tree_nodes_category_id_fkey'), 'skill_tree_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'skill_tree_nodes', 'movement_categories', ['category_id'], ['id'])
    op.drop_column('skill_tree_nodes', 'ascendant_level_required')
    op.drop_column('skill_tree_nodes', 'stat_points_required')
    op.add_column('user_awakening_progress', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user_awakening_progress', sa.Column('quest_id', sa.Integer(), nullable=False))
    op.add_column('user_awakening_progress', sa.Column('progress_reps', sa.Integer(), nullable=False))
    op.add_column('user_awakening_progress', sa.Column('progress_time', sa.Integer(), nullable=False))
    op.add_column('user_awakening_progress', sa.Column('progress_distance', sa.Integer(), nullable=False))
    op.add_column('user_awakening_progress', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.add_column('user_awakening_progress', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('user_awakening_progress', sa.Column('rewards_claimed', sa.Boolean(), nullable=False))
    op.alter_column('user_awakening_progress', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index('idx_user_awakening_progress_completed', 'user_awakening_progress', ['completed_at'], unique=False)
    op.create_index('idx_user_awakening_progress_user_quest', 'user_awakening_progress', ['user_id', 'quest_id'], unique=False)
    op.create_index(op.f('ix_user_awakening_progress_quest_id'), 'user_awakening_progress', ['quest_id'], unique=False)
    op.create_index(op.f('ix_user_awakening_progress_user_id'), 'user_awakening_progress', ['user_id'], unique=False)
    op.drop_constraint(op.f('user_awakening_progress_ascendant_id_fkey'), 'user_awakening_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_awakening_progress', 'awakening_quests', ['quest_id'], ['id'])
    op.drop_column('user_awakening_progress', 'total_sessions')
    op.drop_column('user_awakening_progress', 'updated_at')
    op.drop_column('user_awakening_progress', 'last_session_date')
    op.drop_column('user_awakening_progress', 'longest_streak')
    op.drop_column('user_awakening_progress', 'created_at')
    op.drop_column('user_awakening_progress', 'ascendant_id')
    op.drop_column('user_awakening_progress', 'current_streak')
    op.alter_column('user_skill_progress', 'ascendant_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_skill_progress', 'node_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_skill_progress', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index('idx_user_skill_progress_ascendant_unlocked', 'user_skill_progress', ['ascendant_id', 'unlocked_at'], unique=False)
    op.create_index('idx_user_skill_progress_unlocked_at', 'user_skill_progress', ['unlocked_at'], unique=False)
    op.drop_constraint(op.f('user_skill_progress_node_id_fkey'), 'user_skill_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_skill_progress', 'skill_tree_nodes', ['node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_skill_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_skill_progress_node_id_fkey'), 'user_skill_progress', 'skill_tree_nodes', ['node_id'], ['node_id'])
    op.drop_index('idx_user_skill_progress_unlocked_at', table_name='user_skill_progress')
    op.drop_index('idx_user_skill_progress_ascendant_unlocked', table_name='user_skill_progress')
    op.alter_column('user_skill_progress', 'unlocked_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('user_skill_progress', 'node_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user_skill_progress', 'ascendant_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('user_awakening_progress', sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_awakening_progress', sa.Column('ascendant_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('user_awakening_progress', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user_awakening_progress', sa.Column('longest_streak', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_awakening_progress', sa.Column('last_session_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user_awakening_progress', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user_awakening_progress', sa.Column('total_sessions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_awakening_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_awakening_progress_ascendant_id_fkey'), 'user_awakening_progress', 'ascendants', ['ascendant_id'], ['id'])
    op.drop_index(op.f('ix_user_awakening_progress_user_id'), table_name='user_awakening_progress')
    op.drop_index(op.f('ix_user_awakening_progress_quest_id'), table_name='user_awakening_progress')
    op.drop_index('idx_user_awakening_progress_user_quest', table_name='user_awakening_progress')
    op.drop_index('idx_user_awakening_progress_completed', table_name='user_awakening_progress')
    op.alter_column('user_awakening_progress', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user_awakening_progress', 'rewards_claimed')
    op.drop_column('user_awakening_progress', 'completed_at')
    op.drop_column('user_awakening_progress', 'last_updated')
    op.drop_column('user_awakening_progress', 'progress_distance')
    op.drop_column('user_awakening_progress', 'progress_time')
    op.drop_column('user_awakening_progress', 'progress_reps')
    op.drop_column('user_awakening_progress', 'quest_id')
    op.drop_column('user_awakening_progress', 'user_id')
    op.add_column('skill_tree_nodes', sa.Column('stat_points_required', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('skill_tree_nodes', sa.Column('ascendant_level_required', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'skill_tree_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('skill_tree_nodes_category_id_fkey'), 'skill_tree_nodes', 'movement_categories', ['category_id'], ['category_id'])
    op.drop_index('idx_skill_tree_nodes_level', table_name='skill_tree_nodes')
    op.drop_index('idx_skill_tree_nodes_category_level_unique', table_name='skill_tree_nodes')
    op.drop_column('skill_tree_nodes', 'required_tech_points')
    op.drop_column('skill_tree_nodes', 'required_end_points')
    op.drop_column('skill_tree_nodes', 'required_str_points')
    op.drop_column('skill_tree_nodes', 'required_ascendant_level')
    op.add_column('quests', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('quests', sa.Column('target_exercise', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('quests', sa.Column('target_reps', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quests', sa.Column('quest_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('quests', sa.Column('xp_reward', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quests', type_='foreignkey')
    op.create_foreign_key(op.f('quests_ascendant_id_fkey'), 'quests', 'ascendants', ['ascendant_id'], ['id'])
    op.drop_index(op.f('ix_quests_status'), table_name='quests')
    op.drop_index(op.f('ix_quests_source'), table_name='quests')
    op.drop_index('idx_quests_ascendant_status', table_name='quests')
    op.create_index(op.f('ix_quests_quest_id'), 'quests', ['quest_id'], unique=True)
    op.create_index(op.f('idx_quests_expires_at'), 'quests', ['expires_at'], unique=False)
    op.create_index(op.f('idx_quests_ascendant_id'), 'quests', ['ascendant_id'], unique=False)
    op.alter_column('quests', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('quests', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('quests', 'ascendant_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('quests', 'status')
    op.drop_column('quests', 'source')
    op.add_column('quest_completions', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('quest_completions', sa.Column('xp_earned', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quest_completions', type_='foreignkey')
    op.drop_constraint(None, 'quest_completions', type_='foreignkey')
    op.create_foreign_key(op.f('quest_completions_ascendant_id_fkey'), 'quest_completions', 'ascendants', ['ascendant_id'], ['id'])
    op.drop_constraint(None, 'quest_completions', type_='unique')
    op.drop_index('idx_quest_completions_ascendant_date', table_name='quest_completions')
    op.create_index(op.f('idx_quest_completions_completed_at'), 'quest_completions', ['completed_at'], unique=False)
    op.create_index(op.f('idx_quest_completions_ascendant_id'), 'quest_completions', ['ascendant_id'], unique=False)
    op.alter_column('quest_completions', 'quest_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('quest_completions', 'ascendant_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'movements', type_='foreignkey')
    op.create_foreign_key(op.f('movements_node_id_fkey'), 'movements', 'skill_tree_nodes', ['node_id'], ['node_id'])
    op.drop_index('idx_movements_node_name_unique', table_name='movements')
    op.drop_index('idx_movements_node_id', table_name='movements')
    op.drop_index('idx_movements_name', table_name='movements')
    op.alter_column('movements', 'xp_per_rep',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('movements', 'node_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('movements', 'stat_reward_type')
    op.add_column('movement_categories', sa.Column('category_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('movement_categories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movement_categories', type_='unique')
    op.drop_constraint(None, 'movement_categories', type_='unique')
    op.create_index(op.f('ix_movement_categories_id'), 'movement_categories', ['id'], unique=False)
    op.create_index(op.f('ix_movement_categories_category_id'), 'movement_categories', ['category_id'], unique=True)
    op.alter_column('movement_categories', 'id',
               existing_type=sa.String(length=50),
               server_default=sa.text("nextval('movement_categories_id_seq'::regclass)"),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('movement_categories', 'primary_stat')
    op.alter_column('incursions_v2', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('incursion_participants_v2', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('incursion_participants_v2', 'incursion_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('dungeon_trials', sa.Column('exercise_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('dungeon_trials', sa.Column('target_reps', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dungeon_trials', type_='foreignkey')
    op.create_foreign_key(op.f('dungeon_trials_session_id_fkey'), 'dungeon_trials', 'dungeon_sessions', ['session_id'], ['id'])
    op.drop_index('idx_dungeon_trials_type', table_name='dungeon_trials')
    op.drop_index('idx_dungeon_trials_status', table_name='dungeon_trials')
    op.drop_index('idx_dungeon_trials_started', table_name='dungeon_trials')
    op.drop_index('idx_dungeon_trials_session', table_name='dungeon_trials')
    op.drop_index('idx_dungeon_trials_number', table_name='dungeon_trials')
    op.drop_index('idx_dungeon_trials_completed', table_name='dungeon_trials')
    op.create_index(op.f('idx_dungeon_trials_session_id'), 'dungeon_trials', ['session_id'], unique=False)
    op.drop_column('dungeon_trials', 'trial_data')
    op.drop_column('dungeon_trials', 'started_at')
    op.drop_column('dungeon_trials', 'trial_status')
    op.drop_column('dungeon_trials', 'required_reps')
    op.drop_column('dungeon_trials', 'movement_id')
    op.drop_column('dungeon_trials', 'trial_type')
    op.add_column('dungeon_sessions', sa.Column('session_data', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('dungeon_sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('dungeon_sessions', sa.Column('session_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('dungeon_sessions', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_dungeon_sessions_dungeon_level'), table_name='dungeon_sessions')
    op.drop_index(op.f('ix_dungeon_sessions_ascendant_id'), table_name='dungeon_sessions')
    op.drop_index('idx_dungeon_sessions_level', table_name='dungeon_sessions')
    op.drop_index('idx_dungeon_sessions_keys_spent', table_name='dungeon_sessions')
    op.drop_index('idx_dungeon_sessions_expires', table_name='dungeon_sessions')
    op.drop_index('idx_dungeon_sessions_ascendant', table_name='dungeon_sessions')
    op.drop_index('idx_dungeon_sessions_status', table_name='dungeon_sessions')
    op.create_index(op.f('idx_dungeon_sessions_status'), 'dungeon_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_dungeon_sessions_session_id'), 'dungeon_sessions', ['session_id'], unique=True)
    op.create_index(op.f('idx_dungeon_sessions_ascendant_id'), 'dungeon_sessions', ['ascendant_id'], unique=False)
    op.alter_column('dungeon_sessions', 'session_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('dungeon_sessions', 'shadow_keys_spent',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.add_column('dungeon_rewards', sa.Column('reward_value', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('dungeon_rewards', sa.Column('earned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dungeon_rewards', type_='foreignkey')
    op.drop_constraint(None, 'dungeon_rewards', type_='foreignkey')
    op.create_foreign_key(op.f('dungeon_rewards_session_id_fkey'), 'dungeon_rewards', 'dungeon_sessions', ['session_id'], ['id'])
    op.create_foreign_key(op.f('dungeon_rewards_ascendant_id_fkey'), 'dungeon_rewards', 'ascendants', ['ascendant_id'], ['id'])
    op.drop_index('idx_dungeon_rewards_type', table_name='dungeon_rewards')
    op.drop_index('idx_dungeon_rewards_session', table_name='dungeon_rewards')
    op.drop_index('idx_dungeon_rewards_ascendant', table_name='dungeon_rewards')
    op.drop_index('idx_dungeon_rewards_applied', table_name='dungeon_rewards')
    op.create_index(op.f('idx_dungeon_rewards_ascendant_id'), 'dungeon_rewards', ['ascendant_id'], unique=False)
    op.alter_column('dungeon_rewards', 'reward_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('dungeon_rewards', 'applied_at')
    op.drop_column('dungeon_rewards', 'amount')
    op.add_column('dungeon_progress', sa.Column('last_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dungeon_progress', type_='foreignkey')
    op.create_foreign_key(op.f('dungeon_progress_ascendant_id_fkey'), 'dungeon_progress', 'ascendants', ['ascendant_id'], ['id'])
    op.drop_constraint(None, 'dungeon_progress', type_='unique')
    op.drop_index('idx_dungeon_progress_level', table_name='dungeon_progress')
    op.drop_index('idx_dungeon_progress_last_completion', table_name='dungeon_progress')
    op.drop_index('idx_dungeon_progress_completions', table_name='dungeon_progress')
    op.drop_index('idx_dungeon_progress_ascendant', table_name='dungeon_progress')
    op.create_index(op.f('idx_dungeon_progress_ascendant_id'), 'dungeon_progress', ['ascendant_id'], unique=False)
    op.alter_column('dungeon_progress', 'total_shadow_essence_earned',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('dungeon_progress', 'total_shadow_keys_spent',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('dungeon_progress', 'total_completions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('dungeon_progress', 'ascendant_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('dungeon_level_unlocks', sa.Column('unlocked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('dungeon_level_unlocks', sa.Column('ascendant_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('dungeon_level_unlocks_ascendant_id_fkey'), 'dungeon_level_unlocks', 'ascendants', ['ascendant_id'], ['id'])
    op.drop_index(op.f('ix_dungeon_level_unlocks_dungeon_level'), table_name='dungeon_level_unlocks')
    op.drop_index('idx_dungeon_unlocks_level', table_name='dungeon_level_unlocks')
    op.drop_index('idx_dungeon_unlocks_enabled', table_name='dungeon_level_unlocks')
    op.drop_index('idx_dungeon_unlocks_aura', table_name='dungeon_level_unlocks')
    op.drop_index('idx_dungeon_unlocks_ascendant_level', table_name='dungeon_level_unlocks')
    op.create_index(op.f('idx_dungeon_level_unlocks_ascendant_id'), 'dungeon_level_unlocks', ['ascendant_id'], unique=False)
    op.drop_column('dungeon_level_unlocks', 'unlock_data')
    op.drop_column('dungeon_level_unlocks', 'is_enabled')
    op.drop_column('dungeon_level_unlocks', 'unlock_description')
    op.drop_column('dungeon_level_unlocks', 'required_previous_completion')
    op.drop_column('dungeon_level_unlocks', 'required_skill_tree_progress')
    op.drop_column('dungeon_level_unlocks', 'required_aura')
    op.drop_column('dungeon_level_unlocks', 'required_ascendant_level')
    op.drop_constraint(None, 'dungeon_keys', type_='foreignkey')
    op.create_foreign_key(op.f('dungeon_keys_ascendant_id_fkey'), 'dungeon_keys', 'ascendants', ['ascendant_id'], ['id'])
    op.drop_index('idx_dungeon_keys_ascendant_type', table_name='dungeon_keys')
    op.create_index(op.f('idx_dungeon_keys_ascendant_id'), 'dungeon_keys', ['ascendant_id'], unique=False)
    op.alter_column('dungeon_keys', 'ascendant_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('daily_modifiers', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_daily_modifiers_modifier_date'), table_name='daily_modifiers')
    op.drop_index('idx_daily_modifiers_type', table_name='daily_modifiers')
    op.drop_index('idx_daily_modifiers_active', table_name='daily_modifiers')
    op.drop_index('idx_daily_modifiers_date', table_name='daily_modifiers')
    op.create_index(op.f('idx_daily_modifiers_date'), 'daily_modifiers', ['date'], unique=False)
    op.drop_column('daily_modifiers', 'modifier_data')
    op.drop_column('daily_modifiers', 'skill_point_bonus')
    op.drop_column('daily_modifiers', 'xp_bonus')
    op.drop_column('daily_modifiers', 'modifier_type')
    op.drop_column('daily_modifiers', 'modifier_date')
    op.add_column('awakening_sessions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('awakening_sessions', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('awakening_sessions', sa.Column('ascendant_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'awakening_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('awakening_sessions_ascendant_id_fkey'), 'awakening_sessions', 'ascendants', ['ascendant_id'], ['id'])
    op.drop_index(op.f('ix_awakening_sessions_user_id'), table_name='awakening_sessions')
    op.drop_index(op.f('ix_awakening_sessions_status'), table_name='awakening_sessions')
    op.drop_index(op.f('ix_awakening_sessions_session_date'), table_name='awakening_sessions')
    op.drop_index('idx_awakening_sessions_user_date', table_name='awakening_sessions')
    op.drop_index('idx_awakening_sessions_status', table_name='awakening_sessions')
    op.alter_column('awakening_sessions', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('awakening_sessions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('awakening_sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('awakening_sessions_id_seq'::regclass)"))
    op.drop_column('awakening_sessions', 'reset_at')
    op.drop_column('awakening_sessions', 'reset_used')
    op.drop_column('awakening_sessions', 'status')
    op.drop_column('awakening_sessions', 'tier_level')
    op.drop_column('awakening_sessions', 'user_id')
    op.add_column('awakening_rewards', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('awakening_rewards', sa.Column('reward_value', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('awakening_rewards', sa.Column('earned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('awakening_rewards', sa.Column('reward_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_awakening_rewards_session_id'), table_name='awakening_rewards')
    op.drop_index('idx_awakening_rewards_session', table_name='awakening_rewards')
    op.alter_column('awakening_rewards', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('awakening_rewards', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('awakening_rewards', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('awakening_rewards', 'streak_bonus')
    op.drop_column('awakening_rewards', 'aura_change')
    op.drop_column('awakening_rewards', 'stat_points')
    op.drop_column('awakening_rewards', 'xp_gained')
    op.drop_column('awakening_rewards', 'shadow_keys')
    op.add_column('awakening_quests', sa.Column('target_value', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('awakening_quests', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('awakening_quests', sa.Column('current_progress', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('awakening_quests', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('awakening_quests', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_awakening_quests_status'), table_name='awakening_quests')
    op.drop_index(op.f('ix_awakening_quests_session_id'), table_name='awakening_quests')
    op.drop_index(op.f('ix_awakening_quests_quest_type'), table_name='awakening_quests')
    op.drop_index('idx_awakening_quests_type_status', table_name='awakening_quests')
    op.drop_index('idx_awakening_quests_session', table_name='awakening_quests')
    op.drop_index('idx_awakening_quests_movement', table_name='awakening_quests')
    op.alter_column('awakening_quests', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('awakening_quests', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('awakening_quests', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('awakening_quests', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('awakening_quests', 'progress_distance')
    op.drop_column('awakening_quests', 'progress_time')
    op.drop_column('awakening_quests', 'progress_reps')
    op.drop_column('awakening_quests', 'status')
    op.drop_column('awakening_quests', 'parameters')
    op.drop_column('awakening_quests', 'difficulty_level')
    op.drop_column('awakening_quests', 'target_distance')
    op.drop_column('awakening_quests', 'target_time')
    op.drop_column('awakening_quests', 'target_reps')
    op.drop_column('awakening_quests', 'target_movement')
    op.drop_column('awakening_quests', 'target_movement_id')
    op.drop_index(op.f('ix_ascendants_last_login'), table_name='ascendants')
    op.drop_index(op.f('ix_ascendants_aura'), table_name='ascendants')
    op.drop_constraint(None, 'ascendant_stats', type_='foreignkey')
    op.create_foreign_key(op.f('ascendant_stats_ascendant_id_fkey'), 'ascendant_stats', 'ascendants', ['ascendant_id'], ['id'])
    op.drop_constraint(None, 'ascendant_stats', type_='unique')
    op.drop_index('idx_ascendant_stats_ascendant_id', table_name='ascendant_stats')
    op.alter_column('ascendant_stats', 'tech_value',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'end_value',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'str_value',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'tech_xp',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'end_xp',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'str_xp',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('ascendant_stats', 'ascendant_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('setting_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey')),
    sa.UniqueConstraint('setting_key', name=op.f('system_settings_setting_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_system_settings_key'), 'system_settings', ['setting_key'], unique=False)
    # ### end Alembic commands ###
