"""Initial V2 schema migration

Revision ID: f635a66fc269
Revises: 
Create Date: 2025-07-23 04:23:52.213525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f635a66fc269'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Create V2 tables only."""
    # Create stat_enum type if it doesn't exist
    connection = op.get_bind()
    result = connection.execute(sa.text(
        "SELECT 1 FROM pg_type WHERE typname = 'stat_enum'"
    ))
    if not result.fetchone():
        op.execute("CREATE TYPE stat_enum AS ENUM ('STR', 'END', 'TECH')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ascendants',
    sa.Column('discord_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('global_xp', sa.Integer(), nullable=False),
    sa.Column('aura', sa.Integer(), nullable=False),
    sa.Column('strength_points', sa.Integer(), nullable=False),
    sa.Column('endurance_points', sa.Integer(), nullable=False),
    sa.Column('technique_points', sa.Integer(), nullable=False),
    sa.Column('rested_xp_pool', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ascendants_aura'), 'ascendants', ['aura'], unique=False)
    op.create_index(op.f('ix_ascendants_discord_id'), 'ascendants', ['discord_id'], unique=True)
    op.create_index(op.f('ix_ascendants_id'), 'ascendants', ['id'], unique=False)
    
    op.create_table('movement_categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('primary_stat', postgresql.ENUM('STR', 'END', 'TECH', name='stat_enum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    op.create_table('ascendant_stats',
    sa.Column('ascendant_id', sa.Integer(), nullable=False),
    sa.Column('str_level', sa.Integer(), nullable=False),
    sa.Column('str_xp', sa.Float(), nullable=False),
    sa.Column('end_level', sa.Integer(), nullable=False),
    sa.Column('end_xp', sa.Float(), nullable=False),
    sa.Column('tech_level', sa.Integer(), nullable=False),
    sa.Column('tech_xp', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_level >= 1', name='check_end_level_positive'),
    sa.CheckConstraint('end_xp >= 0', name='check_end_xp_non_negative'),
    sa.CheckConstraint('str_level >= 1', name='check_str_level_positive'),
    sa.CheckConstraint('str_xp >= 0', name='check_str_xp_non_negative'),
    sa.CheckConstraint('tech_level >= 1', name='check_tech_level_positive'),
    sa.CheckConstraint('tech_xp >= 0', name='check_tech_xp_non_negative'),
    sa.ForeignKeyConstraint(['ascendant_id'], ['ascendants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ascendant_id')
    )
    op.create_index(op.f('ix_ascendant_stats_id'), 'ascendant_stats', ['id'], unique=False)
    
    op.create_table('dungeon_keys',
    sa.Column('ascendant_id', sa.Integer(), nullable=False),
    sa.Column('key_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ascendant_id'], ['ascendants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dungeon_keys_id'), 'dungeon_keys', ['id'], unique=False)
    
    op.create_table('dungeon_progress',
    sa.Column('ascendant_id', sa.Integer(), nullable=False),
    sa.Column('highest_level_completed', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ascendant_id'], ['ascendants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ascendant_id')
    )
    op.create_index(op.f('ix_dungeon_progress_id'), 'dungeon_progress', ['id'], unique=False)
    
    op.create_table('quests',
    sa.Column('ascendant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ascendant_id'], ['ascendants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_id'), 'quests', ['id'], unique=False)
    op.create_index(op.f('ix_quests_source'), 'quests', ['source'], unique=False)
    op.create_index(op.f('ix_quests_status'), 'quests', ['status'], unique=False)
    
    op.create_table('skill_tree_nodes',
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_ascendant_level', sa.Integer(), nullable=False),
    sa.Column('required_str_points', sa.Integer(), nullable=False),
    sa.Column('required_end_points', sa.Integer(), nullable=False),
    sa.Column('required_tech_points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level >= 1 AND level <= 5', name='check_level_range'),
    sa.CheckConstraint('required_ascendant_level >= 1', name='check_required_ascendant_level_positive'),
    sa.CheckConstraint('required_end_points >= 0', name='check_required_end_points_non_negative'),
    sa.CheckConstraint('required_str_points >= 0', name='check_required_str_points_non_negative'),
    sa.CheckConstraint('required_tech_points >= 0', name='check_required_tech_points_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['movement_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_tree_nodes_id'), 'skill_tree_nodes', ['id'], unique=False)
    
    op.create_table('movements',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('xp_per_rep', sa.Float(), nullable=False),
    sa.Column('stat_reward_type', postgresql.ENUM('STR', 'END', 'TECH', name='stat_enum', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('xp_per_rep > 0', name='check_xp_per_rep_positive'),
    sa.ForeignKeyConstraint(['node_id'], ['skill_tree_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    
    op.create_table('quest_completions',
    sa.Column('ascendant_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ascendant_id'], ['ascendants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id')
    )
    op.create_index(op.f('ix_quest_completions_id'), 'quest_completions', ['id'], unique=False)
    
    op.create_table('user_skill_progress',
    sa.Column('ascendant_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ascendant_id'], ['ascendants.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['skill_tree_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ascendant_id', 'node_id', name='uq_user_skill_progress_ascendant_node')
    )
    op.create_index(op.f('ix_user_skill_progress_id'), 'user_skill_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Drop V2 tables only."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_skill_progress_id'), table_name='user_skill_progress')
    op.drop_table('user_skill_progress')
    op.drop_index(op.f('ix_quest_completions_id'), table_name='quest_completions')
    op.drop_table('quest_completions')
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_skill_tree_nodes_id'), table_name='skill_tree_nodes')
    op.drop_table('skill_tree_nodes')
    op.drop_index(op.f('ix_quests_status'), table_name='quests')
    op.drop_index(op.f('ix_quests_source'), table_name='quests')
    op.drop_index(op.f('ix_quests_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_dungeon_progress_id'), table_name='dungeon_progress')
    op.drop_table('dungeon_progress')
    op.drop_index(op.f('ix_dungeon_keys_id'), table_name='dungeon_keys')
    op.drop_table('dungeon_keys')
    op.drop_index(op.f('ix_ascendant_stats_id'), table_name='ascendant_stats')
    op.drop_table('ascendant_stats')
    op.drop_table('movement_categories')
    op.drop_index(op.f('ix_ascendants_id'), table_name='ascendants')
    op.drop_index(op.f('ix_ascendants_discord_id'), table_name='ascendants')
    op.drop_index(op.f('ix_ascendants_aura'), table_name='ascendants')
    op.drop_table('ascendants')
    
    # Drop stat_enum type if it exists and no other tables are using it
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT 1 FROM information_schema.columns 
        WHERE udt_name = 'stat_enum' 
        AND table_schema = 'public'
    """))
    if not result.fetchone():
        # No columns are using the enum, safe to drop
        op.execute("DROP TYPE IF EXISTS stat_enum")
    # ### end Alembic commands ###
